package afrl.cmasi.enumerations is

   type WavelengthBandEnum is (AllAny, EO, LWIR, SWIR, MWIR, Other);
   for WavelengthBandEnum use (AllAny => 0, EO => 1, LWIR => 2, SWIR => 3, MWIR => 4, Other => 5);
   
   type AltitudeTypeEnum is (AGL, MSL);
   for AltitudeTypeEnum use (AGL => 0, MSL => 1);
   
   type FOVOperationModeEnum is (Continuous, Discrete);
   for FOVOperationModeEnum use (Continuous => 0, Discrete => 1);
   
   type GimbalPointingModeEnum is (Unknown, AirVehicleRelativeAngle, AirVehicleRelativeSlewRate, LatLonSlaved, InertialRelativeSlewRate, Scan, Stowed);
   for GimbalPointingModeEnum use (Unknown => 0, AirVehicleRelativeAngle => 1, AirVehicleRelativeSlewRate => 2, LatLonSlaved => 3, InertialRelativeSlewRate => 4, Scan => 5, Stowed => 6);
   
   type CmasiEnum is (ABSTRACTGEOMETRY_ENUM,
                      KEYVALUEPAIR_ENUM,
                      LOCATION3D_ENUM,
                      PAYLOADACTION_ENUM,
                      PAYLOADCONFIGURATION_ENUM,
                      PAYLOADSTATE_ENUM,
                      VEHICLEACTION_ENUM,
                      --                     TASK,
                      SEARCHTASK_ENUM,
                      ABSTRACTZONE_ENUM,
                      ENTITYCONFIGURATION_ENUM,
                      FLIGHTPROFILE_ENUM,
                      AIRVEHICLECONFIGURATION_ENUM,
                      ENTITYSTATE_ENUM,
                      AIRVEHICLESTATE_ENUM,
                      WEDGE_ENUM,
                      AREASEARCHTASK_ENUM,
                      CAMERAACTION_ENUM,
                      CAMERACONFIGURATION_ENUM,
                      GIMBALLEDPAYLOADSTATE_ENUM,
                      CAMERASTATE_ENUM,
                      CIRCLE_ENUM,
                      GIMBALANGLEACTION_ENUM,
                      GIMBALCONFIGURATION_ENUM,
                      GIMBALSCANACTION_ENUM,
                      GIMBALSTAREACTION_ENUM,
                      GIMBALSTATE_ENUM,
                      GOTOWAYPOINTACTION_ENUM,
                      KEEPINZONE_ENUM,
                      KEEPOUTZONE_ENUM,
                      LINESEARCHTASK_ENUM,
                      NAVIGATIONACTION_ENUM,
                      LOITERACTION_ENUM,
                      LOITERTASK_ENUM,
                      WAYPOINT_ENUM,
                      MISSIONCOMMAND_ENUM,
                      MUSTFLYTASK_ENUM,
                      OPERATORSIGNAL_ENUM,
                      OPERATINGREGION_ENUM,
                      AUTOMATIONREQUEST_ENUM,
                      POINTSEARCHTASK_ENUM,
                      POLYGON_ENUM,
                      RECTANGLE_ENUM,
                      REMOVETASKS_ENUM,
                      SERVICESTATUS_ENUM,
                      SESSIONSTATUS_ENUM,
                      VEHICLEACTIONCOMMAND_ENUM,
                      VIDEOSTREAMACTION_ENUM,
                      VIDEOSTREAMCONFIGURATION_ENUM,
                      VIDEOSTREAMSTATE_ENUM,
                      AUTOMATIONRESPONSE_ENUM,
                      REMOVEZONES_ENUM,
                      REMOVEENTITIES_ENUM,
                      FLIGHTDIRECTORACTION_ENUM,
                      WEATHERREPORT_ENUM,
                      FOLLOWPATHCOMMAND_ENUM,
                      PATHWAYPOINT_ENUM,
                      STOPMOVEMENTACTION_ENUM,
                      WAYPOINTTRANSFER_ENUM,
                      PAYLOADSTOWACTION_ENUM
                     );
       
   for CmasiEnum use (ABSTRACTGEOMETRY_ENUM => 1,
                      KEYVALUEPAIR_ENUM => 2,
                      LOCATION3D_ENUM => 3,
                      PAYLOADACTION_ENUM => 4,
                      PAYLOADCONFIGURATION_ENUM => 5,
                      PAYLOADSTATE_ENUM => 6,
                      VEHICLEACTION_ENUM => 7,
                      --                     TASK => 8,
                      SEARCHTASK_ENUM => 9,
                      ABSTRACTZONE_ENUM => 10,
                      ENTITYCONFIGURATION_ENUM => 11,
                      FLIGHTPROFILE_ENUM => 12,
                      AIRVEHICLECONFIGURATION_ENUM => 13,
                      ENTITYSTATE_ENUM => 14,
                      AIRVEHICLESTATE_ENUM => 15,
                      WEDGE_ENUM => 16,
                      AREASEARCHTASK_ENUM => 17,
                      CAMERAACTION_ENUM => 18,
                      CAMERACONFIGURATION_ENUM => 19,
                      GIMBALLEDPAYLOADSTATE_ENUM => 20,
                      CAMERASTATE_ENUM => 21,
                      CIRCLE_ENUM => 22,
                      GIMBALANGLEACTION_ENUM => 23,
                      GIMBALCONFIGURATION_ENUM => 24,
                      GIMBALSCANACTION_ENUM => 25,
                      GIMBALSTAREACTION_ENUM => 26,
                      GIMBALSTATE_ENUM => 27,
                      GOTOWAYPOINTACTION_ENUM => 28,
                      KEEPINZONE_ENUM => 29,
                      KEEPOUTZONE_ENUM => 30,
                      LINESEARCHTASK_ENUM => 31,
                      NAVIGATIONACTION_ENUM => 32,
                      LOITERACTION_ENUM => 33,
                      LOITERTASK_ENUM => 34,
                      WAYPOINT_ENUM => 35,
                      MISSIONCOMMAND_ENUM => 36,
                      MUSTFLYTASK_ENUM => 37,
                      OPERATORSIGNAL_ENUM => 38,
                      OPERATINGREGION_ENUM => 39,
                      AUTOMATIONREQUEST_ENUM => 40,
                      POINTSEARCHTASK_ENUM => 41,
                      POLYGON_ENUM => 42,
                      RECTANGLE_ENUM => 43,
                      REMOVETASKS_ENUM => 44,
                      SERVICESTATUS_ENUM => 45,
                      SESSIONSTATUS_ENUM => 46,
                      VEHICLEACTIONCOMMAND_ENUM => 47,
                      VIDEOSTREAMACTION_ENUM => 48,
                      VIDEOSTREAMCONFIGURATION_ENUM => 49,
                      VIDEOSTREAMSTATE_ENUM => 50,
                      AUTOMATIONRESPONSE_ENUM => 51,
                      REMOVEZONES_ENUM => 52,
                      REMOVEENTITIES_ENUM => 53,
                      FLIGHTDIRECTORACTION_ENUM => 54,
                      WEATHERREPORT_ENUM => 55,
                      FOLLOWPATHCOMMAND_ENUM => 56,
                      PATHWAYPOINT_ENUM => 57,
                      STOPMOVEMENTACTION_ENUM => 58,
                      WAYPOINTTRANSFER_ENUM => 59,
                      PAYLOADSTOWACTION_ENUM => 60
                     );

end afrl.cmasi.enumerations;
