using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("-<package_name>-")]
[assembly: AssemblyDescription("An LMCP package generated by LmcpGen.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Air Force Research Laboratory")]
[assembly: AssemblyProduct("-<package_name>-")]
[assembly: AssemblyCopyright("Copyright © Air Force Research Laboratory 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("-<major_version>-.0.0.0")]
[assembly: AssemblyFileVersion("-<major_version>-.0.0.0")]
